logging:
#  file: monasca-transformData.log
  level: INFO

consumerTopic: custom-metrics
producerTopic: metrics
poolFactor: 100

kafka:
  bootstrap.servers: localhost:9092
  group.id: monasca-transformData
  max.threads: 1

tenantId: 1231243
version: v1.0.8