apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: monasca-transform-data
  name: monasca-transform-data
  namespace: monitoring
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: monasca-transform-data
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: CONSUMER_TOPIC
          value: monitor-metrics
        - name: MAX_THREADS
          value: "10"
        - name: KAFKA_URI
          value: 10.110.25.107:9092,10.110.25.105:9092,10.10.6.6:9092
        - name: POOL_FACTOR
          value: 100
        - name: ADMIN_ID
          value: adminid
        image: registry.icp.com:5000/library/iop/lma/monasca-transform-data:v1.0.3
        imagePullPolicy: IfNotPresent
        name: transform-data
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 16000m
            memory: 16Gi
          requests:
            cpu: 8000m
            memory: 2Gi